[build]
  base = "frontend"
  command = "npm install --include=dev && npm run build:prod"
  publish = "dist"

[build.environment]
  VITE_BACKEND_URL = "https://lexassist-backend.onrender.com"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
