services:
  - type: web
    name: lexassist-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_PUBLIC_KEY
        sync: false
      - key: INDIAN_KANOON_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
